/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-102965-gf531a1a4e8-20210713"
#endif /* AVUTIL_FFVERSION_H */
